import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  relative bg-[size:24px_24px] bg-[position:0_0] bg-[linear-gradient(to_right,#f4f4f4,transparent_1px),linear-gradient(to_bottom,#f4f4f4,transparent_1px)]  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
